name: Doxygen GitHub Pages Deploy

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Install conan
        run: pipx install conan
      - name: Conan Profile
        run: |
          conan profile detect --force
      - name: Install Packages with Conan
        run: |
          conan install .
      - name: Build
        run: |
          cmake -S . -B build -DBUILD_TESTS=OFF -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=./build/Release/generators/conan_toolchain.cmake
          cmake --build build
      - uses: DenverCoder1/doxygen-github-pages-action@v2.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN}}