name: Run Tests

on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Install conan
        run: pipx install conan
      - name: Conan Profile
        run: |
          conan profile detect --force
      - name: Install Packages with Conan
        run: |
          conan install .
      - name: Build
        run: |
          cmake -S . -B build -DBUILD_TESTS=ON -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=./build/Release/generators/conan_toolchain.cmake
          cmake --build build
      - name: Test
        run: |
          cd build
          ctest