name: Run Tests

on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Install conan
        run: pipx install conan
      - name: Conan Profile
        run: |
          conan profile detect --force
      - name: Install Packages with Conan
        run: |
          conan install .
      - name: Build
        uses: threeal/cmake-action@v2.1.0
      - name: Test
        uses: threeal/ctest-action@v1.1.0